
/* GENERAL */

UNIT = 25.4; // 25.4 for in - 1 for mm
$FN = 100;

/* COVER */

COVER_BASE_WIDTH = 4 * UNIT;
COVER_BASE_LENGTH = 4 * UNIT;
COVER_BASE_THICKNESS = 0.1 * UNIT;

COVER_HEIGHT = 1.25 * UNIT;
COVER_TOP_SCALE = 0.8;

COVER_HORIZONTAL_PADDING = 0.5 * UNIT;
COVER_VERTICAL_PADDING = 0.5 * UNIT;

/* LEVEL */

LEVEL_HORIZONTAL_PADDING = 0.5 * UNIT;
LEVEl_VERTICAL_PADDING = 0.5 * UNIT;

/* RISERS */

RISER_LENGTH = LEVEl_VERTICAL_PADDING;
